"""Simplified jet tagger (dev/fit accuracy within 0.05 points of the original network)

The simplified JEDI-linear 3-feature / 8-particle jet tagger, written out as explicit code
(generated by make_algorithm.py from version_within_0p05pt.npz). Inputs: the 8 stored particles of a jet, each (pT, Δη, Δφ),
standardised exactly like the network's dataloader (x - mean) / std. Output: 5 class scores (g, q, W, Z, t);
the decision is the largest score.

rnd(v, f) = round v to f fractional bits (floor(v*2^f + 1/2) / 2^f; f may be negative = coarser steps).
Size (per jet): neurons L1/s/d/L3/64/32/16 = 30/13/43/35/59/31/16 (tot 227), weights 1381, relu/jet 693, mult/jet 1234 (+1535 pow2), add/jet 3245, round/jet 1344, wrap/jet 0, inputs 24

Run:  python final_algorithm.py   -> accuracy on all 260,000 test jets and agreement with the simplified network.
"""
import numpy as np


def rnd(v, f):
    return np.floor(v * 2.0 ** f + 0.5) / 2.0 ** f


def rq(v, f, c):          # f fractional bits in this particle slot, or the constant c when the slot does not use it
    return c if f is None else rnd(v, f)


def relu(v):
    return np.maximum(v, 0.0)


# ---- per-slot tables (particle slots 0..7)
F_IN_pt = [4, 4, 4, 4, 4, 5, 5, 6]   # fractional bits per particle slot
F_IN_eta = [6, 5, 5, 4, 4, 4, 3, 3]   # fractional bits per particle slot
F_IN_phi = [6, 4, 4, 4, 4, 4, 3, 3]   # fractional bits per particle slot
F_MSG_1 = [2, 1, 2, 1, 2, 1, 1, 2]   # fractional bits per particle slot
F_MSG_7 = [1, 2, 1, 2, 2, 2, 2, 1]   # fractional bits per particle slot
F_MSG_8 = [1, 2, 2, 2, 3, 3, 2, 2]   # fractional bits per particle slot
F_MSG_11 = [1, 2, 2, 1, 0, -1, -2, -2]   # fractional bits per particle slot
F_A11 = [-2, -2, -2, -3, -5, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_A11 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_MSG_13 = [1, 2, 0, 0, 1, 0, 0, 0]   # fractional bits per particle slot
F_A13 = [0, 1, 0, 0, -1, -2, None, -2]   # fractional bits per particle slot; None = slot does not use it, constant below
C_A13 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_MSG_16 = [2, 2, 1, 2, 2, 2, 2, 2]   # fractional bits per particle slot
F_A16 = [2, 1, 0, 0, -1, -1, -1, -2]   # fractional bits per particle slot
F_MSG_17 = [2, 2, 1, 2, 2, 2, 2, 2]   # fractional bits per particle slot
F_A17 = [-1, -1, -1, -1, -1, -2, -2, -2]   # fractional bits per particle slot
F_MSG_18 = [3, 2, 2, 2, 3, 2, 2, 2]   # fractional bits per particle slot
F_A18 = [1, 1, 0, 0, -1, -1, -1, -2]   # fractional bits per particle slot
F_A19 = [2, 0, 0, -1, 0, 0, -1, 0]   # fractional bits per particle slot
F_MSG_20 = [4, 3, 3, 3, 4, 4, 3, 3]   # fractional bits per particle slot
F_MSG_22 = [1, 2, 1, 2, 3, 2, 3, 4]   # fractional bits per particle slot
F_A22 = [-1, 0, 1, 2, 1, 1, 0, 0]   # fractional bits per particle slot
F_MSG_24 = [3, 3, 2, 3, 2, 3, 2, 2]   # fractional bits per particle slot
F_MSG_29 = [1, 1, 1, 1, 1, 1, 0, 1]   # fractional bits per particle slot
F_A29 = [2, 2, 1, 1, 1, 1, 1, 1]   # fractional bits per particle slot
F_MSG_30 = [2, 2, 2, 2, 2, 3, 3, 3]   # fractional bits per particle slot
F_MSG_35 = [3, 3, 2, 3, 2, 2, 2, 2]   # fractional bits per particle slot
F_A35 = [1, 1, 0, 0, 0, 0, 0, 0]   # fractional bits per particle slot
F_MSG_36 = [3, 1, 1, 2, 2, 2, 2, 1]   # fractional bits per particle slot
F_A36 = [1, 1, 0, 0, 0, -1, 0, -1]   # fractional bits per particle slot
F_MSG_38 = [3, 2, 2, 2, 2, 3, 2, 2]   # fractional bits per particle slot
F_MSG_39 = [2, 2, 2, 3, 2, 3, 3, 2]   # fractional bits per particle slot
F_MSG_40 = [2, 2, 1, 1, 1, 1, 2, 4]   # fractional bits per particle slot
F_A40 = [2, 0, -2, -1, -1, -1, -2, -2]   # fractional bits per particle slot
F_MSG_41 = [3, 3, 2, 2, 2, 2, 2, 2]   # fractional bits per particle slot
F_A41 = [3, 1, 1, 1, 0, 0, 0, 0]   # fractional bits per particle slot
F_A43 = [2, 1, 1, 0, 0, 0, 0, -1]   # fractional bits per particle slot
F_MSG_48 = [-1, -1, 1, 2, 2, 2, 1, 1]   # fractional bits per particle slot
F_A48 = [-2, 0, 0, 0, 0, -1, -1, -3]   # fractional bits per particle slot
F_MSG_49 = [2, 1, 2, 2, 2, 2, 2, 1]   # fractional bits per particle slot
F_A49 = [1, 0, 0, 0, 0, 0, 0, 0]   # fractional bits per particle slot
F_MSG_51 = [2, 3, 2, 2, 2, 2, 2, 2]   # fractional bits per particle slot
F_MSG_56 = [None, None, 2, 4, 4, 3, 3, 2]   # fractional bits per particle slot; None = slot does not use it, constant below
C_MSG_56 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_A56 = [None, -3, 0, 1, 2, 4, 4, 3]   # fractional bits per particle slot; None = slot does not use it, constant below
C_A56 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_MSG_59 = [2, 2, 2, 3, 2, 2, 2, 2]   # fractional bits per particle slot
F_A59 = [2, 2, 1, 0, 1, 0, 0, 0]   # fractional bits per particle slot
F_MSG_60 = [2, 1, 1, 2, 1, 1, 1, 1]   # fractional bits per particle slot
F_A60 = [1, -1, -1, 0, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_A60 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_MSG_62 = [-1, 1, 2, 2, 4, 3, 3, 3]   # fractional bits per particle slot
F_S4 = [0, 0, 0, -1, -1, 0, -1, 0]   # fractional bits per particle slot
F_S6 = [-3, -3, -3, -4, -4, -4, -4, -4]   # fractional bits per particle slot
F_S22 = [None, None, -1, -1, 0, 2, 3, 0]   # fractional bits per particle slot; None = slot does not use it, constant below
C_S22 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_S25 = [1, 1, 1, 1, 2, 1, 2, 0]   # fractional bits per particle slot
F_S29 = [-1, -1, 0, 0, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_S29 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_S44 = [-1, -1, 0, 0, -1, -2, -1, -1]   # fractional bits per particle slot
F_S45 = [0, -1, -1, -2, -2, -2, -2, -3]   # fractional bits per particle slot
F_S50 = [-2, -1, -2, -2, -3, -3, -3, -2]   # fractional bits per particle slot
F_S51 = [0, 1, 0, -1, -1, -3, -3, -4]   # fractional bits per particle slot
F_S53 = [-2, -1, -2, -2, -2, -2, -2, -1]   # fractional bits per particle slot
F_S55 = [2, 1, 2, 1, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_S55 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_S63 = [-1, -2, -1, -1, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_S63 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V0 = [-2, -1, -1, -1, -2, -1, -2, -2]   # fractional bits per particle slot
F_V1 = [-4, -4, -3, -4, -4, -4, -4, -2]   # fractional bits per particle slot
F_V2 = [-1, -1, -1, -1, -1, -1, -1, -2]   # fractional bits per particle slot
F_V4 = [-1, -2, -2, -3, -2, -3, -2, -2]   # fractional bits per particle slot
F_V5 = [-1, -2, -2, -2, -2, -1, -2, -4]   # fractional bits per particle slot
F_V6 = [-4, -5, -5, -5, -5, -5, -5, -5]   # fractional bits per particle slot
F_V10 = [-3, -2, -2, -2, -2, -2, -2, -2]   # fractional bits per particle slot
F_V12 = [-2, -3, -3, -2, -2, -3, -2, -2]   # fractional bits per particle slot
F_V13 = [-3, -3, -4, -4, -4, -5, -5, -5]   # fractional bits per particle slot
F_V14 = [-3, -3, -2, -3, -4, -4, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V14 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V16 = [-4, -4, -5, -4, -4, -5, -4, -4]   # fractional bits per particle slot
F_V17 = [-3, -2, -2, -2, -2, -2, -3, -2]   # fractional bits per particle slot
F_V18 = [-3, -1, -1, -1, 0, -1, -1, 0]   # fractional bits per particle slot
F_V19 = [-1, -1, 0, 0, -1, -1, 0, 0]   # fractional bits per particle slot
F_V20 = [-2, -2, -3, -2, -2, -2, -2, -2]   # fractional bits per particle slot
F_V21 = [-2, -2, -3, -3, -2, -3, -4, -2]   # fractional bits per particle slot
F_V22 = [None, None, -4, -2, -2, -2, -1, -1]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V22 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V23 = [0, 0, -1, 0, -1, -1, -1, 0]   # fractional bits per particle slot
F_V24 = [-3, -3, -3, -3, -3, -3, -3, -5]   # fractional bits per particle slot
F_V25 = [-1, -1, -1, -1, -2, -2, -2, -2]   # fractional bits per particle slot
F_V29 = [-2, -2, -3, -2, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V29 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V30 = [-2, -3, -3, -2, -3, -3, -3, -2]   # fractional bits per particle slot
F_V31 = [-3, -3, -3, -3, -3, -3, -3, -2]   # fractional bits per particle slot
F_V33 = [-3, -3, -4, -3, -3, -3, -3, -3]   # fractional bits per particle slot
F_V34 = [0, 0, 0, -1, 0, -1, 0, -3]   # fractional bits per particle slot
F_V35 = [None, None, -2, None, None, 2, 2, 3]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V35 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V36 = [-3, -2, -2, -2, -2, -2, -3, -2]   # fractional bits per particle slot
F_V40 = [-6, -5, -5, -5, -5, -5, -5, -5]   # fractional bits per particle slot
F_V42 = [-3, -4, -4, -4, None, -4, -5, -6]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V42 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V43 = [-4, -4, -4, -4, -4, -4, -6, -6]   # fractional bits per particle slot
F_V44 = [-2, -2, -2, -2, -4, -4, -4, -5]   # fractional bits per particle slot
F_V45 = [-2, -2, -2, -3, -3, -3, -3, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V45 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V46 = [-3, -2, -3, -2, -2, -2, -2, -2]   # fractional bits per particle slot
F_V48 = [0, 0, 0, -2, 0, 0, 0, 0]   # fractional bits per particle slot
F_V50 = [-3, -2, -2, -3, -3, -3, -3, -3]   # fractional bits per particle slot
F_V51 = [-2, -1, -2, -2, -3, -4, -5, -5]   # fractional bits per particle slot
F_V52 = [-3, -3, -4, -3, -3, -3, -4, -3]   # fractional bits per particle slot
F_V53 = [-3, -4, -4, -4, -4, -4, -4, -5]   # fractional bits per particle slot
F_V55 = [1, 0, -1, -1, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_V55 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_V57 = [0, -1, -1, 0, -1, -1, -1, -1]   # fractional bits per particle slot
F_V63 = [-1, -2, -2, -2, -3, -3, -4, -4]   # fractional bits per particle slot
F_T0 = [1, 1, 1, 0, 0, -1, -1, -1]   # fractional bits per particle slot
F_T2 = [0, 0, 1, 0, 1, 0, 1, 0]   # fractional bits per particle slot
F_T4 = [0, 0, 0, 0, 0, 0, -1, -1]   # fractional bits per particle slot
F_T5 = [1, 1, 1, 1, 2, 2, 2, 1]   # fractional bits per particle slot
F_T7 = [0, -2, -2, -3, -5, -5, -5, -5]   # fractional bits per particle slot
F_T8 = [-1, -2, -2, -2, -1, -2, -2, -2]   # fractional bits per particle slot
F_T11 = [0, -1, -1, 0, 0, 0, 1, 1]   # fractional bits per particle slot
F_T13 = [0, -1, 0, 0, 0, 0, 0, -1]   # fractional bits per particle slot
F_T14 = [0, 0, 0, 0, 0, 0, 0, -1]   # fractional bits per particle slot
F_T17 = [-1, -1, 0, -1, -2, -2, -3, -4]   # fractional bits per particle slot
F_T19 = [0, -1, -1, -1, -1, -1, -1, -1]   # fractional bits per particle slot
F_T22 = [-2, -1, -2, -2, -2, -2, -3, -2]   # fractional bits per particle slot
F_T26 = [-1, 0, 0, 0, 0, 1, 1, 0]   # fractional bits per particle slot
F_T27 = [None, None, None, None, None, 3, 3, 2]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T27 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_T29 = [0, 0, 0, -1, -1, -3, -5, -6]   # fractional bits per particle slot
F_T30 = [None, None, -2, -2, -3, -1, -1, -1]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T30 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_T31 = [1, 1, 1, 1, 1, 1, 2, 1]   # fractional bits per particle slot
F_T32 = [-1, -1, -1, 0, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T32 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_T34 = [-2, -1, -2, -2, -2, -2, -2, -2]   # fractional bits per particle slot
F_T35 = [-1, -1, -1, -2, -1, -1, -1, -1]   # fractional bits per particle slot
F_T37 = [0, 1, 0, 0, 1, -1, 0, -1]   # fractional bits per particle slot
F_T38 = [-1, 0, -1, -1, 0, 0, -1, 0]   # fractional bits per particle slot
F_T40 = [-1, -1, -1, -1, -1, 0, -1, -1]   # fractional bits per particle slot
F_T42 = [-1, -1, -1, -1, -1, -1, -1, 0]   # fractional bits per particle slot
F_T47 = [-1, -1, -1, -1, -1, -2, -1, -2]   # fractional bits per particle slot
F_T48 = [-1, 0, -1, -1, -2, -1, -1, -2]   # fractional bits per particle slot
F_T50 = [-2, -1, -1, -1, -1, -1, -2, -1]   # fractional bits per particle slot
F_T54 = [0, -1, -1, -2, None, None, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T54 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_T56 = [0, -1, -2, -2, -2, -2, -2, -2]   # fractional bits per particle slot
F_T61 = [None, None, None, -1, 1, 1, 2, 0]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T61 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
F_T63 = [-1, -1, -2, -2, -2, -2, None, None]   # fractional bits per particle slot; None = slot does not use it, constant below
C_T63 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


def _algorithm(pt, eta, phi, zeros):
    msg = {}                                  # Σ over particles of layer-1 values
    s_q = {}                                  # layer-2 values per particle
    for p in range(8):
        pt_ = rnd(pt[:, p], F_IN_pt[p])
        eta_ = rnd(eta[:, p], F_IN_eta[p])
        phi_ = rnd(phi[:, p], F_IN_phi[p])
        a0 = relu(-4*pt_ + 6.4375)    # layer-1 neuron 0
        msg[0] = msg.get(0, 0.0) + rnd(a0, 1)
        a0_ = rnd(a0, 1)
        a1 = relu(4*phi_ - 0.9375)    # layer-1 neuron 1
        msg[1] = msg.get(1, 0.0) + rnd(a1, F_MSG_1[p])
        a7 = relu(3*phi_ - 4)    # layer-1 neuron 7
        msg[7] = msg.get(7, 0.0) + rnd(a7, F_MSG_7[p])
        a8 = relu(-2*pt_ - 3*eta_ - 4.3125)    # layer-1 neuron 8
        msg[8] = msg.get(8, 0.0) + rnd(a8, F_MSG_8[p])
        a11 = relu(16*pt_ + 1.625)    # layer-1 neuron 11
        msg[11] = msg.get(11, 0.0) + rnd(a11, F_MSG_11[p])
        a11_ = rq(a11, F_A11[p], C_A11[p])
        a13 = relu(4*pt_ - 4*phi_ + 0.375)    # layer-1 neuron 13
        msg[13] = msg.get(13, 0.0) + rnd(a13, F_MSG_13[p])
        a13_ = rq(a13, F_A13[p], C_A13[p])
        a16 = relu(pt_ + 6*eta_ - 8*phi_ + 0.21875)    # layer-1 neuron 16
        msg[16] = msg.get(16, 0.0) + rnd(a16, F_MSG_16[p])
        a16_ = rnd(a16, F_A16[p])
        a17 = relu(0.5*pt_ - 4.5*eta_ + 4*phi_ - 3.3125)    # layer-1 neuron 17
        msg[17] = msg.get(17, 0.0) + rnd(a17, F_MSG_17[p])
        a17_ = rnd(a17, F_A17[p])
        a18 = relu(1.25*pt_ + 7.5*phi_ - 2.6875)    # layer-1 neuron 18
        msg[18] = msg.get(18, 0.0) + rnd(a18, F_MSG_18[p])
        a18_ = rnd(a18, F_A18[p])
        a19 = relu(11*eta_ + 6*phi_)    # layer-1 neuron 19
        msg[19] = msg.get(19, 0.0) + rnd(a19, 2)
        a19_ = rnd(a19, F_A19[p])
        a20 = relu(0.375*pt_ + 3.75*eta_ - 2.8125)    # layer-1 neuron 20
        msg[20] = msg.get(20, 0.0) + rnd(a20, F_MSG_20[p])
        a22 = relu(-11*pt_ - 1.25)    # layer-1 neuron 22
        msg[22] = msg.get(22, 0.0) + rnd(a22, F_MSG_22[p])
        a22_ = rnd(a22, F_A22[p])
        a24 = relu(0.25*pt_ - 5.5*phi_ - 3.6875)    # layer-1 neuron 24
        msg[24] = msg.get(24, 0.0) + rnd(a24, F_MSG_24[p])
        a29 = relu(5*eta_ - 4.5*phi_ - 0.96875)    # layer-1 neuron 29
        msg[29] = msg.get(29, 0.0) + rnd(a29, F_MSG_29[p])
        a29_ = rnd(a29, F_A29[p])
        a30 = relu(-4*eta_ - 4*phi_ + 4.125)    # layer-1 neuron 30
        msg[30] = msg.get(30, 0.0) + rnd(a30, F_MSG_30[p])
        a31 = relu(1.5*pt_ - 4.5*eta_ + 4*phi_ + 0.96875)    # layer-1 neuron 31
        msg[31] = msg.get(31, 0.0) + rnd(a31, 2)
        a35 = relu(0.5*pt_ - 4*eta_ - 4.5*phi_ - 2.3125)    # layer-1 neuron 35
        msg[35] = msg.get(35, 0.0) + rnd(a35, F_MSG_35[p])
        a35_ = rnd(a35, F_A35[p])
        a36 = relu(-10*phi_)    # layer-1 neuron 36
        msg[36] = msg.get(36, 0.0) + rnd(a36, F_MSG_36[p])
        a36_ = rnd(a36, F_A36[p])
        a38 = relu(4.5*eta_ - 2.5*phi_ + 0.015625)    # layer-1 neuron 38
        msg[38] = msg.get(38, 0.0) + rnd(a38, F_MSG_38[p])
        a39 = relu(2*pt_ + 8*eta_ + 1.125)    # layer-1 neuron 39
        msg[39] = msg.get(39, 0.0) + rnd(a39, F_MSG_39[p])
        a40 = relu(8*phi_ + 4.53125)    # layer-1 neuron 40
        msg[40] = msg.get(40, 0.0) + rnd(a40, F_MSG_40[p])
        a40_ = rnd(a40, F_A40[p])
        a41 = relu(0.5*pt_ + 5.25*eta_ + 7*phi_)    # layer-1 neuron 41
        msg[41] = msg.get(41, 0.0) + rnd(a41, F_MSG_41[p])
        a41_ = rnd(a41, F_A41[p])
        a43 = relu(1.25*pt_ - 11*eta_ - 0.75*phi_ - 0.46875)    # layer-1 neuron 43
        msg[43] = msg.get(43, 0.0) + rnd(a43, 2)
        a43_ = rnd(a43, F_A43[p])
        a48 = relu(-6*pt_ + 3*phi_ - 3.75)    # layer-1 neuron 48
        msg[48] = msg.get(48, 0.0) + rnd(a48, F_MSG_48[p])
        a48_ = rnd(a48, F_A48[p])
        a49 = relu(-4*eta_ + 8*phi_)    # layer-1 neuron 49
        msg[49] = msg.get(49, 0.0) + rnd(a49, F_MSG_49[p])
        a49_ = rnd(a49, F_A49[p])
        a51 = relu(-3.5*eta_ - 3.5)    # layer-1 neuron 51
        msg[51] = msg.get(51, 0.0) + rnd(a51, F_MSG_51[p])
        a56 = relu(-11*pt_ - 4.5)    # layer-1 neuron 56
        msg[56] = msg.get(56, 0.0) + rq(a56, F_MSG_56[p], C_MSG_56[p])
        a56_ = rq(a56, F_A56[p], C_A56[p])
        a59 = relu(-8*eta_ + 2.5*phi_)    # layer-1 neuron 59
        msg[59] = msg.get(59, 0.0) + rnd(a59, F_MSG_59[p])
        a59_ = rnd(a59, F_A59[p])
        a60 = relu(0.5*pt_ + 6*eta_ - 1.8125)    # layer-1 neuron 60
        msg[60] = msg.get(60, 0.0) + rnd(a60, F_MSG_60[p])
        a60_ = rq(a60, F_A60[p], C_A60[p])
        a62 = relu(-4*pt_ + 3*eta_ - 3.5)    # layer-1 neuron 62
        msg[62] = msg.get(62, 0.0) + rnd(a62, F_MSG_62[p])
        s4 = relu(0.25*a11_ - 5*a19_ - 6*a36_ - 2*a49_ - 6*a59_ + 62)    # layer-2 neuron 4
        s_q[p, 4] = rnd(s4, F_S4[p])
        s6 = relu(a11_ - 32*a49_ + 48)    # layer-2 neuron 6
        s_q[p, 6] = rnd(s6, F_S6[p])
        s22 = relu(14*a56_ - 4)    # layer-2 neuron 22
        s_q[p, 22] = rq(s22, F_S22[p], C_S22[p])
        s25 = relu(-3.5*a0_ + 0.25*a17_ + 4.5*a29_ + 1.5*a35_ + 1.625*a36_ + 3.75*a41_ + 2.75*a43_ + 2*a49_ - 4*a56_ - 18)    # layer-2 neuron 25
        s_q[p, 25] = rnd(s25, F_S25[p])
        s29 = relu(1.375*a11_ - 10*a43_ + 1.5*a60_)    # layer-2 neuron 29
        s_q[p, 29] = rq(s29, F_S29[p], C_S29[p])
        s41 = relu(0.5*a16_ - 3.5)    # layer-2 neuron 41
        s_q[p, 41] = rnd(s41, 1)
        s44 = 2*a43_    # layer-2 neuron 44
        s_q[p, 44] = rnd(s44, F_S44[p])
        s45 = relu(1.25*a11_ - 8*a16_ + 4*a18_ - 6*a48_ - 2)    # layer-2 neuron 45
        s_q[p, 45] = rnd(s45, F_S45[p])
        s50 = relu(6*a13_ - 16*a18_ - 16*a22_ + 2*a36_)    # layer-2 neuron 50
        s_q[p, 50] = rnd(s50, F_S50[p])
        s51 = relu(1.5*a0_ - a11_ + 12*a22_)    # layer-2 neuron 51
        s_q[p, 51] = rnd(s51, F_S51[p])
        s53 = relu(1.875*a11_ - 8*a19_ - 8*a36_ - 16*a56_ - 12*a59_ + 80)    # layer-2 neuron 53
        s_q[p, 53] = rnd(s53, F_S53[p])
        s55 = relu(0.34375*a11_ - 6*a41_)    # layer-2 neuron 55
        s_q[p, 55] = rq(s55, F_S55[p], C_S55[p])
        s63 = relu(a11_ - 16*a40_ - 8)    # layer-2 neuron 63
        s_q[p, 63] = rq(s63, F_S63[p], C_S63[p])
    # ---- jet level: message (mean over particles of layer-1 values) -> d
    m0 = rnd(msg[0] * 0.125, 3)
    m1 = rnd(msg[1] * 0.125, 3)
    m7 = rnd(msg[7] * 0.125, 3)
    m8 = rnd(msg[8] * 0.125, 4)
    m11 = rnd(msg[11] * 0.125, 3)
    m13 = rnd(msg[13] * 0.125, 2)
    m16 = rnd(msg[16] * 0.125, 2)
    m17 = rnd(msg[17] * 0.125, 3)
    m18 = rnd(msg[18] * 0.125, 4)
    m19 = rnd(msg[19] * 0.125, 2)
    m20 = rnd(msg[20] * 0.125, 5)
    m22 = rnd(msg[22] * 0.125, 4)
    m24 = rnd(msg[24] * 0.125, 4)
    m29 = rnd(msg[29] * 0.125, 1)
    m30 = rnd(msg[30] * 0.125, 3)
    m31 = rnd(msg[31] * 0.125, 2)
    m35 = rnd(msg[35] * 0.125, 4)
    m36 = rnd(msg[36] * 0.125, 2)
    m38 = rnd(msg[38] * 0.125, 3)
    m39 = rnd(msg[39] * 0.125, 3)
    m40 = rnd(msg[40] * 0.125, 3)
    m41 = rnd(msg[41] * 0.125, 2)
    m43 = rnd(msg[43] * 0.125, 2)
    m48 = rnd(msg[48] * 0.125, 3)
    m49 = rnd(msg[49] * 0.125, 3)
    m51 = rnd(msg[51] * 0.125, 4)
    m56 = rnd(msg[56] * 0.125, 4)
    m59 = rnd(msg[59] * 0.125, 3)
    m60 = rnd(msg[60] * 0.125, 3)
    m62 = rnd(msg[62] * 0.125, 5)
    d0 = rnd(relu(5*m17 - 40*m20 - 12*m24 - 7*m29 + 29), 0)    # d-neuron 0
    d1 = rnd((7*m11 - 4), -2)    # d-neuron 1
    d2 = rnd(relu(0.5*m16 + 9*m17 + 4*m18 + 0.5*m19 + m30 - 8*m31 + 2.5*m39 - 3.5*m40 + 6*m48), 0)    # d-neuron 2
    d3 = rnd(relu(-6*m17 + 0.75*m29 - 5.5*m35 - 2*m43 - 16*m51 + 24.5), 1)    # d-neuron 3
    d4 = rnd(relu(4*m1 - 1.25*m11 + 1.5*m16 + 0.875*m19 + m36 + 2*m43), 1)    # d-neuron 4
    d5 = rnd(relu(20*m8 + 0.5*m16 - m31 + 7.5*m39 - 3.5*m43 + 2*m48 - 20*m62), 1)    # d-neuron 5
    d7 = rnd(relu(1.25*m0 - 2.625*m11 + 3.75*m22 + 3.5*m56 + 10), 2)    # d-neuron 7
    d8 = rnd(relu(m11 - 64*m20 + 0.5*m30 + 7*m43 - 32*m60), -1)    # d-neuron 8
    d10 = rnd(relu(-32*m7 + 0.25*m11 - 12*m18 - 16*m20 + 0.5*m35 + 2.5*m36 + 21), 0)    # d-neuron 10
    d12 = rnd(relu(6*m13 - 12*m17 - 24*m18 + 4*m29 + 2*m30), -1)    # d-neuron 12
    d13 = rnd(relu(-16*m1 - 32*m17 + 4*m24 + 4*m29 + 8*m31), -3)    # d-neuron 13
    d14 = rnd(relu(-16*m35 - 2*m48 + 12), -1)    # d-neuron 14
    d16 = rnd(relu(-20*m16 + 8*m17 - 40*m36 + 12*m39 + 8*m40), -3)    # d-neuron 16
    d17 = rnd(relu(10*m7 - 2*m19 + 26*m20 + 10*m30 - 6*m35 - 6*m39 + 0.5*m43 - 12), 0)    # d-neuron 17
    d18 = rnd(relu(10*m8 + m16 + 3*m17 - 1.25*m29 - 0.5*m31 + 1.75*m39 - 2*m43 + 7*m51 - 4*m59 + 1.75), 0)    # d-neuron 18
    d19 = rnd(relu(-3*m8 - 1.625*m16 - 3*m17 + 5*m20 + 3.5*m24 + 3*m31 - 0.25*m39 + 2.25*m40 + 0.625*m43 - 4*m48 + 0.5*m59 - 15.5), 2)    # d-neuron 19
    d20 = rnd(relu(5.5*m19 - 24*m35 - 16*m51), -1)    # d-neuron 20
    d21 = rnd(relu(8*m8 - 3*m30 + 8*m35 + 2*m39 + 5*m40 - 2*m43 - 2), -1)    # d-neuron 21
    d23 = rnd(relu(-4.5*m36 + 8*m38 + 1.25*m39 - 5.5*m41 + 2.25*m59), 0)    # d-neuron 23
    d24 = rnd(relu(3*m29 + 9*m30 - 7*m39 - 6*m41 + 4*m43), -2)    # d-neuron 24
    d26 = rnd(relu(-4*m16 + 2.375*m19 + 2.5*m43 - 6.5*m49 + 3.25), 1)    # d-neuron 26
    d30 = rnd((-24*m1 - 12*m30 + 14*m40), -1)    # d-neuron 30
    d31 = rnd(relu(4*m16 - 64*m18 + 4*m30 - 16*m49), -2)    # d-neuron 31
    d32 = rnd(relu(-4*m13 - 64*m35 + 3.5*m40 + 4*m59), -2)    # d-neuron 32
    d33 = rnd(relu(8*m19 - 24*m41 - 8*m49 + 4*m59 + 24), -2)    # d-neuron 33
    d34 = rnd(relu(0.5*m13 + 0.5*m18 + 3.125*m36 - 10*m38 + 2.125*m41 - 4.5*m59 + 1.5), 1)    # d-neuron 34
    d35 = rnd((2*m56), 3)    # d-neuron 35
    d36 = rnd(relu(-8*m19 + 3*m30 + 3*m31 + 1.5*m36 - 12*m41), -2)    # d-neuron 36
    d37 = rnd(relu(m24 - 1.5*m30 + 0.75*m35 + m39 + 1.5*m40 - 4*m48 + 3*m51 - 7.75), 0)    # d-neuron 37
    d39 = rnd(relu(-4*m13 + 6*m18 - 80*m24 - 4*m29 + 6*m40), -1)    # d-neuron 39
    d40 = rnd(relu(6*m36 + m40 - 32*m43 + 16*m60), -3)    # d-neuron 40
    d41 = rnd((1.5*m1 + 0.25*m7 - 0.1875*m11 + 0.25*m13 + 1.125*m16 + m18 + 2.125*m19 + m20 + 0.75*m30 + 1.75*m35 + 1.875*m36 + m38 + 0.625*m43 + 0.375*m49 + 2.5*m59 - 3), 3)    # d-neuron 41
    d42 = rnd(relu(m0 + 3*m19 + 8*m29 - 12*m59), -2)    # d-neuron 42
    d43 = rnd(relu(-16*m16 + 12*m31 + 4*m35 + 4*m40), -2)    # d-neuron 43
    d44 = rnd(relu(3.25*m30 + 2*m31 - 9*m39 + 24*m62), 0)    # d-neuron 44
    d45 = rnd(relu(-8*m24 + 7), 1)    # d-neuron 45
    d46 = rnd(relu(-64*m17 + 2.5*m19 + 2*m36 - 8*m49 - 6*m59), -1)    # d-neuron 46
    d48 = rnd(relu(4*m11 - 7*m22 + 0.125*m49 - 15.5), 1)    # d-neuron 48
    d50 = rnd(relu(8*m7 - 3*m40 + 24), 1)    # d-neuron 50
    d52 = rnd(relu(-16*m16 - 8*m29 - 32*m38 + 6*m40 + 3*m43), -2)    # d-neuron 52
    d57 = rnd(relu(1.75*m16 - 4*m19 + 0.25*m31 + 0.5*m36 - 4.25*m43 + 4*m49), 0)    # d-neuron 57
    d62 = rnd(relu(3*m16 - 16*m17 - 6*m31 + 22), -1)    # d-neuron 62
    d63 = rnd((4*m7 + 0.5*m11 + 2*m13 - 0.5*m40 + m60 - 5), 0)    # d-neuron 63
    pooled = {}
    for p in range(8):
        v0 = rnd((d0), F_V0[p])
        v1 = rnd((d1), F_V1[p])
        v2 = rnd((d2), F_V2[p])
        v3 = rnd((d3), -1)
        v4 = rnd((s_q[p, 4] + d4), F_V4[p])
        v5 = rnd((d5), F_V5[p])
        v6 = rnd((s_q[p, 6]), F_V6[p])
        v7 = rnd((d7), 0)
        v8 = rnd((d8), -3)
        v10 = rnd((d10), F_V10[p])
        v12 = rnd((d12), F_V12[p])
        v13 = rnd((d13), F_V13[p])
        v14 = rq((d14), F_V14[p], C_V14[p])
        v16 = rnd((d16), F_V16[p])
        v17 = rnd((d17), F_V17[p])
        v18 = rnd((d18), F_V18[p])
        v19 = rnd((d19), F_V19[p])
        v20 = rnd((d20), F_V20[p])
        v21 = rnd((d21), F_V21[p])
        v22 = rq((s_q[p, 22]), F_V22[p], C_V22[p])
        v23 = rnd((d23), F_V23[p])
        v24 = rnd((d24), F_V24[p])
        v25 = rnd((s_q[p, 25]), F_V25[p])
        v26 = rnd((d26), -1)
        v29 = rq((s_q[p, 29]), F_V29[p], C_V29[p])
        v30 = rnd((d30), F_V30[p])
        v31 = rnd((d31), F_V31[p])
        v32 = rnd((d32), -3)
        v33 = rnd((d33), F_V33[p])
        v34 = rnd((d34), F_V34[p])
        v35 = rq((d35), F_V35[p], C_V35[p])
        v36 = rnd((d36), F_V36[p])
        v37 = rnd((d37), 0)
        v39 = rnd((d39), -3)
        v40 = rnd((d40), F_V40[p])
        v41 = rnd((s_q[p, 41] + d41), 0)
        v42 = rq((d42), F_V42[p], C_V42[p])
        v43 = rnd((d43), F_V43[p])
        v44 = rnd((s_q[p, 44] + d44), F_V44[p])
        v45 = rq((s_q[p, 45] + d45), F_V45[p], C_V45[p])
        v46 = rnd((d46), F_V46[p])
        v48 = rnd((d48), F_V48[p])
        v50 = rnd((s_q[p, 50] + d50), F_V50[p])
        v51 = rnd((s_q[p, 51]), F_V51[p])
        v52 = rnd((d52), F_V52[p])
        v53 = rnd((s_q[p, 53]), F_V53[p])
        v55 = rq((s_q[p, 55]), F_V55[p], C_V55[p])
        v57 = rnd((d57), F_V57[p])
        v62 = rnd((d62), -2)
        v63 = rnd((s_q[p, 63] + d63), F_V63[p])
        t0 = relu(0.375*v25 + 0.09375*v29 - 0.5*v51 - 0.03125*v53 - 8)    # layer-3 neuron 0
        pooled[0] = pooled.get(0, 0.0) + rnd(t0, F_T0[p])
        t2 = relu(0.75*v3 + 0.375*v10 + 0.25*v12 - 0.5*v19 - v37 + 0.25*v62 + 6)    # layer-3 neuron 2
        pooled[2] = pooled.get(2, 0.0) + rnd(t2, F_T2[p])
        t4 = relu(0.75*v5 - 0.25*v8 - 0.125*v24)    # layer-3 neuron 4
        pooled[4] = pooled.get(4, 0.0) + rnd(t4, F_T4[p])
        t5 = relu(-0.0625*v1 + 0.5*v25 + 0.25*v41 - 9)    # layer-3 neuron 5
        pooled[5] = pooled.get(5, 0.0) + rnd(t5, F_T5[p])
        t7 = relu(0.125*v1 + 0.125*v24 + 0.25*v42 + 0.25*v52 + 0.4375*v53 - 52)    # layer-3 neuron 7
        pooled[7] = pooled.get(7, 0.0) + rnd(t7, F_T7[p])
        t8 = relu(-v5 + 0.75*v8)    # layer-3 neuron 8
        pooled[8] = pooled.get(8, 0.0) + rnd(t8, F_T8[p])
        t11 = relu(-0.25*v0 + 0.6875*v4 - 0.125*v10 - 0.25*v13 - 0.5*v25 - 0.0625*v39 + 0.09375*v53 - 29)    # layer-3 neuron 11
        pooled[11] = pooled.get(11, 0.0) + rnd(t11, F_T11[p])
        t13 = 1.5*v7    # layer-3 neuron 13
        pooled[13] = pooled.get(13, 0.0) + rnd(t13, F_T13[p])
        t14 = 0.375*v20 + 0.375*v39    # layer-3 neuron 14
        pooled[14] = pooled.get(14, 0.0) + rnd(t14, F_T14[p])
        t15 = relu(-v23 - v26 - v34 + 0.4375*v41 - v57 + 7)    # layer-3 neuron 15
        pooled[15] = pooled.get(15, 0.0) + rnd(t15, 1)
        t16 = relu(0.5*v3 - 0.5*v24 + 0.5*v32 + 0.25*v40 - 0.5*v44)    # layer-3 neuron 16
        pooled[16] = pooled.get(16, 0.0) + rnd(t16, -1)
        t17 = relu(-0.5*v29 + 0.5*v44 + 0.75*v45 - 0.5*v51)    # layer-3 neuron 17
        pooled[17] = pooled.get(17, 0.0) + rnd(t17, F_T17[p])
        t19 = relu(0.625*v30 - 0.25*v50)    # layer-3 neuron 19
        pooled[19] = pooled.get(19, 0.0) + rnd(t19, F_T19[p])
        t22 = relu(0.25*v16 - 0.5*v42 + 0.25*v44 + 0.5*v52 - 0.5*v62)    # layer-3 neuron 22
        pooled[22] = pooled.get(22, 0.0) + rnd(t22, F_T22[p])
        t26 = relu(-0.0625*v8 + 0.5625*v25 - 34)    # layer-3 neuron 26
        pooled[26] = pooled.get(26, 0.0) + rnd(t26, F_T26[p])
        t27 = relu(0.1875*v22 - 2.5*v35)    # layer-3 neuron 27
        pooled[27] = pooled.get(27, 0.0) + rq(t27, F_T27[p], C_T27[p])
        t29 = relu(0.375*v50 - v51 - 0.1875*v53 + 1.5*v55)    # layer-3 neuron 29
        pooled[29] = pooled.get(29, 0.0) + rnd(t29, F_T29[p])
        t30 = 0.75*v22    # layer-3 neuron 30
        pooled[30] = pooled.get(30, 0.0) + rq(t30, F_T30[p], C_T30[p])
        t31 = relu(0.25*v0 - 0.3125*v4 + 0.125*v10 - 0.75*v18 - 0.0625*v21 - 0.3125*v41 - 0.15625*v53 + 34)    # layer-3 neuron 31
        pooled[31] = pooled.get(31, 0.0) + rnd(t31, F_T31[p])
        t32 = relu(-0.625*v4 + 1.25*v29 - 0.125*v45)    # layer-3 neuron 32
        pooled[32] = pooled.get(32, 0.0) + rq(t32, F_T32[p], C_T32[p])
        t34 = relu(-0.25*v3 + 0.375*v10 - 0.25*v32 + 0.75*v33 + v36)    # layer-3 neuron 34
        pooled[34] = pooled.get(34, 0.0) + rnd(t34, F_T34[p])
        t35 = 1.5*v48    # layer-3 neuron 35
        pooled[35] = pooled.get(35, 0.0) + rnd(t35, F_T35[p])
        t37 = relu(0.6875*v25 - 22)    # layer-3 neuron 37
        pooled[37] = pooled.get(37, 0.0) + rnd(t37, F_T37[p])
        t38 = relu(0.5*v2 + 0.125*v6 - 0.0625*v16 + 0.25*v17 - 0.375*v21)    # layer-3 neuron 38
        pooled[38] = pooled.get(38, 0.0) + rnd(t38, F_T38[p])
        t40 = relu(0.25*v5 - 0.125*v43 + 0.375*v50)    # layer-3 neuron 40
        pooled[40] = pooled.get(40, 0.0) + rnd(t40, F_T40[p])
        t41 = relu(-0.6875*v41 + 0.25*v45 + 0.28125*v53 + 40)    # layer-3 neuron 41
        pooled[41] = pooled.get(41, 0.0) + rnd(t41, 1)
        t42 = relu(-0.5*v6 + 1.5*v19)    # layer-3 neuron 42
        pooled[42] = pooled.get(42, 0.0) + rnd(t42, F_T42[p])
        t47 = relu(-0.25*v4 + 0.5*v44 - 0.5*v51 - 2)    # layer-3 neuron 47
        pooled[47] = pooled.get(47, 0.0) + rnd(t47, F_T47[p])
        t48 = relu(-0.25*v4 + 0.25*v5 + 0.5*v14 + 0.75*v45 - 0.25*v51 - 2*v55)    # layer-3 neuron 48
        pooled[48] = pooled.get(48, 0.0) + rnd(t48, F_T48[p])
        t50 = relu(0.5*v17 - 12)    # layer-3 neuron 50
        pooled[50] = pooled.get(50, 0.0) + rnd(t50, F_T50[p])
        t54 = relu(-0.5*v4 + 3.75*v55)    # layer-3 neuron 54
        pooled[54] = pooled.get(54, 0.0) + rq(t54, F_T54[p], C_T54[p])
        t56 = relu(0.1875*v6 - 0.25*v51 + 1.25*v63 - 16)    # layer-3 neuron 56
        pooled[56] = pooled.get(56, 0.0) + rnd(t56, F_T56[p])
        t60 = relu(-0.5*v16 + 0.75*v31 - 0.5*v43 + 1.5*v46)    # layer-3 neuron 60
        pooled[60] = pooled.get(60, 0.0) + rnd(t60, -2)
        t61 = relu(-0.15625*v1 + 0.71875*v22 - 27)    # layer-3 neuron 61
        pooled[61] = pooled.get(61, 0.0) + rq(t61, F_T61[p], C_T61[p])
        t63 = relu(-v4 + 0.875*v45)    # layer-3 neuron 63
        pooled[63] = pooled.get(63, 0.0) + rq(t63, F_T63[p], C_T63[p])
    # ---- jet level: pooled (Σ over particles / 16) -> dense 64 -> dense 32 -> dense 16 -> 5 class scores
    h0 = rnd(pooled[0] * 0.0625, 4)
    h2 = rnd(pooled[2] * 0.0625, 1)
    h4 = rnd(pooled[4] * 0.0625, 1)
    h5 = rnd(pooled[5] * 0.0625, 3)
    h7 = rnd(pooled[7] * 0.0625, 2)
    h8 = rnd(pooled[8] * 0.0625, 0)
    h11 = rnd(pooled[11] * 0.0625, 2)
    h13 = rnd(pooled[13] * 0.0625, 1)
    h14 = rnd(pooled[14] * 0.0625, 1)
    h15 = rnd(pooled[15] * 0.0625, 1)
    h16 = rnd(pooled[16] * 0.0625, 0)
    h17 = rnd(pooled[17] * 0.0625, 1)
    h19 = rnd(pooled[19] * 0.0625, 0)
    h22 = rnd(pooled[22] * 0.0625, -1)
    h26 = rnd(pooled[26] * 0.0625, 2)
    h27 = rnd(pooled[27] * 0.0625, 5)
    h29 = rnd(pooled[29] * 0.0625, 2)
    h30 = rnd(pooled[30] * 0.0625, 1)
    h31 = rnd(pooled[31] * 0.0625, 2)
    h32 = rnd(pooled[32] * 0.0625, 2)
    h34 = rnd(pooled[34] * 0.0625, -1)
    h35 = rnd(pooled[35] * 0.0625, 0)
    h37 = rnd(pooled[37] * 0.0625, 3)
    h38 = rnd(pooled[38] * 0.0625, 1)
    h40 = rnd(pooled[40] * 0.0625, 1)
    h41 = rnd(pooled[41] * 0.0625, 2)
    h42 = rnd(pooled[42] * 0.0625, 1)
    h47 = rnd(pooled[47] * 0.0625, 2)
    h48 = rnd(pooled[48] * 0.0625, 2)
    h50 = rnd(pooled[50] * 0.0625, 0)
    h54 = rnd(pooled[54] * 0.0625, 1)
    h56 = rnd(pooled[56] * 0.0625, 2)
    h60 = rnd(pooled[60] * 0.0625, -1)
    h61 = rnd(pooled[61] * 0.0625, 2)
    h63 = rnd(pooled[63] * 0.0625, 2)
    x0 = rnd(relu(0.5*h11 - h13 + 0.75*h15 - 2*h26 - 8*h27 + 0.75*h35 - 0.125*h42 - 8*h61 + 11.5), 0)
    x1 = rnd(relu(-0.34375*h2 + h17 + 0.1875*h22 - 0.5*h29 - 0.125*h38 - 0.75*h40 + 0.25*h41 + 0.4375*h42 + 0.125*h48 - 1.25*h56 - 0.5*h61 + 1.25*h63), 1)
    x2 = rnd(relu(2*h29 - 4*h48), -1)
    x3 = rnd(relu(0.1875*h2 + 0.5*h4 - 1.25*h17 + 0.5*h26 + 0.625*h29 - 0.125*h31 + h32 + 0.3125*h40 - 5.25), 0)
    x4 = rnd(relu(0.5*h2 - 0.25*h5 + 2*h27 - 0.5*h37 - 0.125*h41 + 0.125*h60 - 0.25), 1)
    x5 = rnd(relu(-h7 - h11 + 0.375*h41 - 3), 0)
    x6 = rnd(relu(-0.5*h7 + 2*h11 - 0.75*h14 + 0.625*h15 + 0.25*h26 + 0.5*h29 + 0.625*h34 + 0.125*h40 - 0.1875*h41 - h48 + 0.25*h60 - 2), 0)
    x7 = rnd(relu(-0.5*h5 - 0.09375*h22 - 2*h37 - 0.1875*h60 + 4.25), 3)
    x8 = rnd(relu(0.375*h8 - 0.25*h29 + 0.75*h37 - 0.1875*h41), 1)
    x9 = rnd(relu(-8*h27 + 0.875*h35), -1)
    x10 = rnd(relu(0.1875*h2 - 0.125*h30 - 2*h61), 2)
    x11 = rnd(relu(1.5*h11 - 0.1875*h13 + 0.625*h15 - 0.75*h16 - 0.5*h22 + 0.5*h26 - 0.25*h34 - 0.3125*h41 - 0.375*h60 + 8.5), 0)
    x12 = rnd(relu(-0.0625*h2 + 0.1875*h5 - 0.5*h13 + 0.0625*h15 - 8*h27 - h30 - 0.5*h41 + 0.5*h47 + 0.375*h48 + 13), 0)
    x13 = rnd(relu(-0.0625*h8 - 2*h11 - 0.75*h13 - 0.75*h15 + 0.375*h30 + 0.125*h41 + 9), 0)
    x14 = rnd(relu(0.5*h11 + 1.0625*h41 - 0.5*h48 - h63 - 20), -1)
    x15 = rnd(relu(h15 - h31 - 0.5*h34 + 0.5*h37 - 1), -1)
    x17 = rnd(relu(5*h0 + 0.5*h15 + 0.125*h16 + 0.125*h22 - 0.375*h31 - 0.375*h41 + 0.5*h54 + h63 + 0.5), 0)
    x18 = rnd(relu(0.5625*h4 + 0.375*h19 - 0.0625*h22 + 0.5*h26 - 0.5*h29 + 0.5*h32 - 0.125*h34 + 0.015625*h41 + 0.25*h48 - h50 - h54 - 1), 1)
    x19 = rnd(relu(-0.0625*h2 - 0.25*h4 - 0.25*h16 - h32 + 0.09375*h35 + 0.125*h38 - 0.25*h41 + 0.75*h47 + 3.25), 1)
    x20 = rnd(relu(-0.5*h14 + 1.5*h37 - 5), 0)
    x21 = rnd(relu(0.1875*h4 - 1.5*h7 + 0.84375*h13 + 0.125*h22 + 4*h27 - 0.5*h31 + 0.625*h37 + 0.25*h38 + 0.75*h50 + 0.03125*h60), 1)
    x22 = rnd(relu(-2*h11 - 0.25*h19 - 8*h27 + 0.375*h35 - 0.375*h41 + 5), 0)
    x23 = rnd(relu(0.25*h13 - 1.5*h26 + 12*h61), 0)
    x24 = rnd(relu(1.5*h0 - 16*h27 - h30 + 3.5), 0)
    x25 = rnd(relu(0.875*h13 - 0.25*h17 - 0.03125*h19 + 3*h27 - h29 + 0.25*h30 - h32 - 0.5*h35 + 0.34375*h41 - 0.75*h48 - h54 - 0.5*h63 - 7), 0)
    x26 = rnd(relu(h11 - 0.5*h13 + 0.3125*h22 + 4*h27 - 0.75*h29 + 0.875*h30 - h31 + 0.1875*h34 - 0.5*h48 + 0.125*h60 + 4), 1)
    x27 = rnd(relu(h11 + 0.0625*h13 + 0.25*h15 + 0.0625*h22 - 20*h27 - 1.375*h30 - 0.25*h32 - 2*h61 + 15.5), 1)
    x28 = rnd(relu(5.5*h0 + 0.5*h5 + 1.75*h11 - 1.25*h26 - 0.375*h35 - 0.375*h41 + 0.25), 1)
    x29 = rnd(relu(0.15625*h2 - 0.75*h7 - 0.0625*h13 - 0.28125*h14 - 0.25*h16 - 0.25*h19 + 0.75*h29 + 0.15625*h34 + 0.5625*h38 + 0.4375*h40 - 0.078125*h41 - 1.125*h48 + 0.75*h54 + 0.75*h56 - 1.375), 2)
    x30 = rnd(relu(-0.625*h2 + 0.375*h8 + 0.75*h14 + 0.375*h15 + 0.625*h16 + 0.1875*h22 + 0.25*h41 - 0.25*h42 - 2.5*h56 - 0.25*h60 - 1.5), -1)
    x31 = rnd(relu(-0.25*h13 + h16 + 0.25*h22 - 2*h37 + 0.25*h40 + 0.25*h48 + 0.5*h60), -1)
    x32 = rnd(relu(-16*h0 + 0.375*h31 + 2), 1)
    x33 = rnd(relu(0.75*h5 - 12*h11 + 0.125*h19 - 0.25*h41 + 1.5), 0)
    x34 = rnd(relu(0.5*h0 - 0.1875*h2 + 0.0625*h4 + 0.5625*h5 - h11 + 0.109375*h13 - 0.09375*h22 - 0.09375*h31 - 0.1875*h41 + 0.1875*h48 - 0.25), 3)
    x35 = rnd(relu(0.15625*h2 + 0.5*h7 - 0.125*h17 + 0.75*h41 - 0.5*h48 - 6.375), 0)
    x36 = rnd(relu(0.75*h35 + 2*h61 - 3.2578125), 0)
    x37 = rnd(relu(0.5*h19 + 0.25*h42 - 4), 0)
    x38 = rnd(relu(-h7 - 0.25*h13 - 0.5*h22 + 0.25*h29 + 0.75*h32 + 0.25*h40 + h56 - 4*h63), -1)
    x39 = rnd(relu(-h4 + 0.375*h17 + 0.0625*h31 - 2*h32 + 3.25*h47 - 0.25*h48 + 0.25*h50 + 2.25*h54 - 2.5), 0)
    x40 = rnd(relu(-4*h11 + 0.3125*h13 - 1.5*h15 + 4*h27 - h35 + 0.75*h37 + 0.25*h41 + 6*h61), 1)
    x41 = rnd(relu(-0.25*h0 + 0.21875*h2 - 0.03125*h4 - 0.25*h5 + 0.21875*h14 - 0.125*h19 - 2.25*h26 + 0.375*h31 - 0.1875*h38 + 0.46875*h41 - 0.0625*h42 - 0.1875*h50 + 1.625), 2)
    x43 = rnd(relu(-1.375*h5 + 0.5*h7 - 0.5*h29 + 0.375*h30 + 0.25*h41 - h47 + 4*h61 + 8), 1)
    x44 = rnd(relu(-0.125*h2 - 0.375*h31 + 0.25*h37 + 0.375*h42 + 0.25*h48 - h56 + 0.125), 2)
    x45 = rnd(relu(-0.5*h15 - 2*h26 + 0.125*h31 - 1.5*h37 + 0.40625*h41 + 1), 1)
    x47 = rnd(relu(0.5*h16 - 0.5*h31 + 1), 0)
    x48 = rnd(relu(-h4 + h11 - h17 + 0.4375*h41 + 2*h61 - 11.5), 1)
    x50 = rnd(relu(-0.0625*h2 + h8 - 0.5*h16 + 0.375*h22 - 4*h32 + 0.25*h34), 0)
    x51 = rnd(relu(0.4375*h2 + 0.3125*h4 - h7 - 0.5*h8 + 0.5*h11 + 0.25*h15 + 0.25*h16 - 1.25*h17 - 1.125*h31 + h32 - 0.4375*h34 + 0.75*h48 + 0.125*h60 + 2), 0)
    x52 = rnd(relu(-0.5*h8 - h11 - 1.5*h15 - 0.25*h16 - 0.125*h22 - 8*h27 + 0.3125*h41 + 0.375*h42 + 0.25*h50 + 0.5*h54 - 0.75*h60 - 4*h61 + 6.5), 0)
    x53 = rnd(relu(-0.1875*h2 - 3*h29 + 0.03125*h41 + 1.25*h48 - h56 + h63 + 2), 0)
    x54 = rnd(relu(-0.5*h11 - 0.5*h15 + 0.125*h16 + 0.75*h17 + 0.5*h29 + h32 - 0.375*h38 - 0.375*h41 - 0.125*h42 + 0.5*h48 - 0.25), 1)
    x55 = rnd(relu(-h5 - 0.0625*h13 + 0.875*h31), 1)
    x56 = rnd(relu(-0.25*h2 + 0.25*h41), 1)
    x58 = rnd(relu(-2*h5 - 2*h37 + 0.0625*h41 + 3), 1)
    x59 = rnd(relu(3*h26 + 0.5*h38 + 0.125*h42 + h63 - 7), -1)
    x60 = rnd(relu(2*h0 + 0.375*h2 + 0.5*h29 - h63 - 7), 0)
    x61 = rnd(relu(0.375*h2 + 0.25*h13 + 0.3125*h16 + 0.0625*h19 + 0.1875*h22 + 0.625*h31 + 0.125*h34 - 2*h37 + 0.25*h48 + h56 - 14), 0)
    x62 = rnd(relu(0.5*h5 + 0.5*h17 + 1.75*h35 - 8*h61 - 15), -1)
    x63 = rnd(relu(0.375*h4 + 1.25*h5 + 0.875*h11 + 0.25*h15 + 0.375*h19 - 0.5*h34 + 0.5*h38 + 0.25*h42 + h63 - 13.5), 0)
    y0 = rnd(relu(0.0625*x0 + 1.25*x12 + 0.1875*x14 - x15 + 0.25*x24 + 0.625*x33 + x48 - 0.5*x55 - 1.5), -1)
    y1 = rnd(relu(-0.125*x1 - 0.09375*x3 - 0.015625*x6 + 0.40625*x7 + 0.1875*x8 + 0.0625*x10 - 0.0625*x17 - 0.1875*x18 - 0.125*x19 - 0.125*x21 - 0.09375*x28 - 0.15625*x29 - 0.015625*x32 - 0.046875*x33 - 0.375*x34 - 0.03125*x37 - 0.09375*x39 + 0.375*x41 - 0.1875*x44 - 0.03125*x54 + 0.03125*x55 + 0.0625*x58 + 0.03125*x62 + 1.75), 3)
    y2 = rnd(relu(-0.125*x0 - 0.1875*x3 - 0.25*x5 - 0.1875*x13 + 0.21875*x14 + 0.1875*x21 + 0.46875*x25 - 0.25*x36 - 0.1875*x39 - 0.25*x53 - 0.25*x55 + 0.25), 2)
    y3 = rnd(relu(0.09375*x0 + 0.125*x9 + 0.125*x12 - 0.1875*x14 + 0.0625*x18 - 0.09375*x21 - 0.125*x22 + 0.375*x24 - 0.375*x25 + 0.34375*x27 - 0.125*x37 - 0.1875*x40 - 0.75*x48 + 0.125*x55 + 2), 2)
    y4 = rnd(relu(0.5*x34 - x41 + 0.66015625), 1)
    y5 = rnd(relu(-0.5*x19 - 0.75*x34 - 0.1875*x35 - 0.125*x39 - 0.3125*x43 + 0.125*x52 - 0.0625*x53 + 0.5*x54 - 0.5*x59 - 0.125*x61 + 0.125*x62 + 5), 2)
    y6 = rnd(relu(0.125*x15 - 0.1875*x25 - 0.125*x27 - 0.25*x43 - x45 - 0.3125*x59 + 4.5), 0)
    y7 = rnd(relu(-0.125*x0 - 0.5*x10 + 0.125*x17 - 0.5*x20 - 0.125*x31 - 0.1875*x33 - 0.125*x40 - 0.5*x43 - 0.125*x47 - 0.25*x50 + 0.25*x54 - 0.5*x55 + 3.25), 2)
    y8 = rnd(relu(0.25*x1 + 0.125*x4 - 0.5*x8 - 0.3125*x14 - x17 + 0.5*x29 + 0.25*x30 + 0.1875*x31 - 0.5*x33 - 0.375*x35 + 0.125*x43 + 0.375*x50 + 0.375*x51), 1)
    y9 = rnd(relu(0.5*x3 - 0.25*x5 - 0.0625*x6 - 0.125*x11 + 0.125*x13 - 0.25*x24 - 0.0625*x30 - 0.25*x31 + 0.375*x39 + 0.5*x53 - 0.25*x60 - 0.25), 1)
    y10 = rnd(relu(0.28125*x0 + 0.375*x5 - 0.5*x12 - 0.125*x21 + 0.1875*x25 + 0.25*x27 + 0.625*x32 - 0.125*x53), 2)
    y11 = rnd(relu(0.375*x15 - 0.5*x23 + 0.25*x26 + 0.3125*x27 - 0.75*x40 + 0.4375*x63 - 5), 0)
    y12 = rnd(relu(0.1875*x2 + 0.0625*x23 + 0.0625*x25 + 0.5*x26 - 0.125*x27 - 0.375*x28 - 0.0625*x30 - 0.125*x31 + 0.25*x43 - 0.09375*x50 - 0.0625*x58 - 0.125*x60 - 0.09375*x62 + 2), 2)
    y13 = rnd(relu(-0.25*x1 - 0.125*x25 + 0.375*x26 - 0.109375*x27 - 0.1875*x29 - 0.5*x34 + 0.09375*x41 - 0.1875*x51 + 0.125*x52 - 0.125*x59 - 0.25*x62 + 2), 1)
    y14 = rnd(relu(-0.5*x7 - 0.125*x8 + 0.125*x29 - 0.375*x41 + 1.8671875), 2)
    y15 = rnd(relu(-0.1875*x0 - 0.1875*x6 + 0.25*x13 - 0.0625*x17 - 0.25*x19 - 0.1875*x30 - 0.375*x33 - 0.125*x38 - 0.25*x40 - 0.5*x44 - 0.0625*x50 - 0.1875*x51 - 0.25*x54 - 0.125*x60 + 0.125*x61 + 8), 2)
    y16 = rnd(relu(-0.5*x0 - 0.5*x9 + 0.125*x23 - 0.25*x24 - 0.1875*x25 + 0.125*x26 - 0.1875*x27 + 0.1875*x28 - 0.125*x43 + 4.5), 1)
    y17 = rnd(relu(0.125*x0 - 0.5*x4 + 0.125*x11 + 0.125*x12 - 0.1875*x30 - 0.375*x43 - 0.25*x45 - 0.125*x50 - 0.25*x55 - 0.25*x56 - 0.125*x60 - 0.28125*x63 + 9.75), 1)
    y18 = rnd(relu(0.125*x0 + 0.375*x1 + 0.3125*x6 - 0.625*x11 + 0.5*x19 - 0.25*x23 + 0.25*x29 + 0.25*x30 - 0.125*x36 - 0.375*x45 + 0.3125*x51 - 0.375*x52 - 1.5*x61 + 0.07421875), 1)
    y19 = rnd(relu(-0.625*x1 - 0.25*x3 + 0.125*x5 - 0.5*x12 - 0.0625*x13 - 0.5*x18 - 0.125*x22 - 0.09375*x27 - 0.5*x28 - 0.625*x29 + 0.34375*x35 - 0.125*x39 + 0.25*x43 - 0.125*x50 - 0.25*x51 + 0.09375*x52 - 0.25*x54 + 0.1875*x55), 1)
    y20 = rnd(relu(0.375*x1 + 0.125*x3 + 0.1875*x12 + 0.3125*x18 + 0.375*x19 + 0.03125*x21 + 0.25*x28 + 0.4375*x29 + 0.0625*x31 + 0.4375*x34 + 0.125*x38 + 0.1875*x39 - 0.5*x41 + 0.125*x44 + 0.1875*x51 + 0.125*x54 - 5.8828125), 1)
    y21 = rnd(relu(-0.125*x0 - 0.125*x1 - 0.375*x6 - 0.25*x15 + 0.125*x17 - 0.5*x20 - 0.125*x25 - 0.125*x30 - 0.125*x35 - 0.0625*x39 - 0.375*x45 - 0.25*x51 + 0.09375*x52 + 0.1875*x54 + 3.25), 2)
    y22 = rnd(relu(-0.375*x4 - 0.375*x6 + 0.125*x9 + 0.1875*x22 + 0.25*x29 - 0.375*x30 - 0.0625*x35 + 0.25*x37 - 0.125*x40 - 0.5*x41 - 0.125*x43 - 0.5*x45 - 0.125*x47 + 0.3125*x52 + 0.25*x54 - 0.75*x61 + 0.125*x62 + 4.5), 1)
    y23 = rnd(relu(0.03125*x3 - 0.125*x10 + 0.0625*x18 - 0.125*x35 - 0.0625*x45 + 0.125*x47 - 0.03125*x50 - 0.125*x56 - 0.0625*x63 + 0.3125), 3)
    y24 = rnd(relu(-0.875*x7 - 0.0625*x11 - 0.125*x12 - 0.125*x13 + 0.125*x15 + 0.28125*x21 + 0.1875*x28 + 0.09375*x30 + 0.0625*x33 - 0.5*x36 + 0.125*x37 - 0.25*x41 - 0.375*x45 + 0.09375*x50 + 2.25), 2)
    y25 = rnd(relu(-0.375*x1 - 0.0625*x2 - 0.375*x3 - 0.25*x6 - 0.25*x9 - 0.375*x12 - 0.75*x14 - 0.25*x18 - 0.1875*x21 - 0.0625*x30 - 0.25*x35 - 0.375*x39 + 0.34375*x41 + 0.25*x52 - 0.125*x53 - 0.5*x61 + 8), 1)
    y26 = rnd(relu(0.03125*x1 + 0.25*x3 - 0.1875*x9 + 0.375*x13 - 0.25*x17 - 0.375*x25 + 0.5*x38 + 0.375*x39 + 0.3125*x43 + 0.5*x44 - 0.0625*x52 + 0.125*x53 - 0.25*x63 - 5.75), 1)
    y27 = rnd(relu(0.03125*x0 + 0.375*x1 + 0.25*x3 + 0.125*x13 + 0.375*x18 + 0.03125*x27 + 0.375*x29 + 0.125*x31 - 0.25*x33 - 0.3125*x35 + 0.25*x39 - 0.25*x40 - 0.4375*x45 + 0.0625*x53 - 1.75), 2)
    y29 = rnd(relu(0.125*x6 - 0.125*x13 - 0.1875*x21 - 0.5*x22 - 0.125*x37 + 0.3125*x41 + 0.125*x51 - 0.1875*x52 + 0.1875*x55 + 0.75*x58 - 0.5), 1)
    y30 = rnd(relu(-0.5*x0 - 0.25*x13 + 0.125*x21 + 0.125*x23 + 0.15625*x25 - 0.25*x27 + 0.25*x35 - 0.5*x36 + 0.0625*x37 + 0.1875*x40 - 0.125*x41 + 0.5*x48 + 0.0625*x52 + 0.75), 2)
    y31 = rnd(relu(0.25*x11 - 0.25*x23 - 0.09375*x25 + 0.25*x43 - 0.5*x63), 2)
    z0 = rnd(relu(-0.1875*y1 - 0.0625*y2 - 0.25*y7 - 0.25*y8 - 0.25*y11 + 0.3125*y15 - 0.25*y18 - 0.09375*y19 + 0.625*y21 - 0.125*y22 - 0.1875*y24 - 0.125*y26 - 0.25*y29 + 1.75), 3)
    z1 = rnd(relu(0.125*y0 - 0.09375*y1 + 0.03125*y2 + 0.15625*y3 - 0.0625*y6 + 0.0625*y7 + 0.125*y8 - 0.21875*y10 - 0.25*y16 + 0.125*y22 + 0.125*y23 - 0.0625*y25 + 0.03125*y27 + 1.26171875), 3)
    z2 = rnd(relu(-0.09375*y0 + 0.21875*y2 + 0.21875*y3 - 0.09375*y8 + 0.25*y10 - 0.3125*y13 - 0.0625*y24 + 0.125*y29 + 0.03125*y30 - 0.25), 4)
    z3 = rnd(relu(0.4375*y4 - 0.375*y13 - 0.234375*y20 + 0.375*y21 + 0.375*y22 + 0.5*y23 + 0.4375*y24 - 0.25*y25 - 2.66015625), 3)
    z4 = rnd(relu(0.25*y0 - 0.09375*y2 + 0.375*y5 + 0.75*y6 - 0.375*y11 + 0.75*y18 - y19 - 0.375*y20 + 0.15625*y24), 2)
    z5 = rnd(relu(-0.40625*y2 - 0.25*y3 + 0.0625*y11 + 0.3125*y12 + 0.28125*y19 + 0.125*y22 - 0.1875*y25 + 0.25*y26 + 2), 3)
    z6 = rnd(relu(0.015625*y0 - 0.1875*y1 + 0.03125*y3 - 0.03125*y6 + 0.140625*y8 - 0.21875*y11 - 0.21875*y15 + 0.125*y17 + 0.1875*y19 + 0.0625*y22 + 0.5*y23 + 0.125*y24 - 0.1875*y25 + 0.3125*y27 + 0.28125*y30), 3)
    z7 = rnd(relu(-0.34375*y1 + 0.125*y5 + 0.09375*y8 - 0.1875*y12 - 0.5*y14 - 0.0625*y15 + 0.09375*y17 - 0.375*y18 - 1.25*y20 + 0.3125*y22 - 0.0625*y24 - 0.03125*y25 + 0.125*y26 + 4.5), 3)
    z8 = rnd(relu(-0.375*y8 - 0.1875*y12 + 0.21875*y15 - 0.5*y17 + 0.1875*y25 + 0.25), 3)
    z9 = rnd(relu(-0.03125*y0 + 0.4375*y1 + 0.125*y2 + 0.25*y4 - 0.09375*y8 + 0.21875*y10 + 0.15625*y11 + 0.21875*y12 - 0.25*y17 + 0.21875*y19 - 0.25*y22 + 0.25*y25 - 0.4375*y26 - 2.875), 2)
    z10 = rnd(relu(-0.0625*y0 - 0.125*y9 + 0.28125*y11 - 0.15625*y12 + 0.0625*y13 - 0.1875*y15 - 0.1875*y22 + 0.09375*y25 - 0.21875*y29 - 0.09375*y30 - 0.125*y31 + 4.00390625), 4)
    z11 = rnd((0.4375*y5 + 0.09375*y15 - 0.125*y16 + 0.0625*y17 - 0.25*y19 - 0.5*y23 - 0.25*y24 + 0.1875*y25 - 0.4375*y27 + 1.75), 4)
    z12 = rnd(relu(-0.375*y6 - 0.125*y16 - 0.375*y17 + 0.25*y20 + 0.25*y21 + 0.21875*y22 - 2.12109375), 3)
    z13 = rnd(relu(-0.0625*y0 + 0.25*y6 + 0.21875*y7 + 0.125*y9 + 0.125*y10 - 0.28125*y20 - 0.25*y21 - 0.109375*y25 - 0.4375*y30 + 0.3125*y31 + 4.125), 3)
    z14 = rnd(relu(-0.875*y1 - 0.046875*y3 - 0.0625*y4 + 0.0625*y7 - 0.09375*y13 + 0.09375*y15 + 0.1640625*y17 - 0.125*y18 - 0.25*y20 + 0.34375*y21 - 0.15625*y24 + 1.40625), 4)
    z15 = rnd(relu(-0.3125*y1 + 0.125*y5 + 0.25*y7 + 0.125*y9 - 0.3125*y13 - 0.1875*y15 + 0.1875*y16 - 0.5*y20 + 0.3125*y22 + 0.25*y26 + 0.0625*y27 + 0.9375), 3)
    score_g = -0.15625*z0 + 0.390625*z1 + 0.4296875*z2 - 0.03125*z4 - 0.1875*z5 + 0.109375*z6 + 0.171875*z9 - 0.4375
    score_q = -0.09375*z4 + 0.046875*z5 + 0.125*z6 + 0.0625*z8 + 0.25390625*z9 - 0.125*z10 + 0.0625*z15 + 0.03125
    score_W = 0.34375*z0 - 0.03125*z1 - 0.5*z3 - 0.3125*z6 + 0.21875*z7 - 0.25*z8 - 0.03125*z9 + 0.375*z11 + 0.0703125*z13 - 0.75*z14 - 0.6875*z15 - 0.125
    score_Z = 0.125*z1 - 0.5625*z3 + 0.078125*z4 + 0.015625*z5 - 0.375*z6 + 0.46875*z7 - 0.03125*z9 + 0.0546875*z13 + 0.375*z14 - 0.15625*z15 - 0.09375
    score_t = 0.015625*z0 + 0.0625*z3 + 0.125*z4 - 0.25*z5 + 0.1875*z8 + 0.375*z10 - 0.5*z12 - 0.40625*z13 + 1.34375
    return np.stack([score_g, score_q, score_W, score_Z, score_t], 1)


def classify(pt, eta, phi):
    """pt, eta, phi: arrays (J, 8) of standardised particle features. Returns (J, 5) class scores g, q, W, Z, t."""
    zeros = np.zeros(pt.shape[0])
    return _algorithm(pt, eta, phi, zeros)


if __name__ == '__main__':
    import json, sys
    from pathlib import Path
    import h5py
    ROOT = Path(__file__).resolve().parents[5]
    D = ROOT / 'data'
    st = json.loads((D / 'norm_stats.json').read_text())['8']
    X = np.load(D / 'val_ptetaphi_f16.npy', mmap_mode='r')[:, :8].astype(np.float32)
    X = ((X - np.float32(st['shift'])) / np.float32(st['scale'])).astype(np.float64)
    y = h5py.File(D / 'val_meta.h5')['label'][:]
    S = np.concatenate([classify(X[i:i + 50000, :, 0], X[i:i + 50000, :, 1], X[i:i + 50000, :, 2]) for i in range(0, len(X), 50000)])
    pred = S.argmax(1)
    print(f'test jets: {len(y)}  accuracy: {(pred == y).mean():.5f}')
    if len(sys.argv) > 1:   # optional: compare with the simplified network (JAX) decisions saved in a .npy file
        ref = np.load(sys.argv[1]); print('agreement with the simplified network:', (ref == pred).mean(), 'differ:', int((ref != pred).sum()))
